# configuration of redis is in initializers/redis.rb
# configuration of resque and resque-scheduler is in initializers/resque.rb

# Heroku is on UTC time (EST + 4)

create_daily_forecast:
  cron: 0 11 * * *
  class: AllForecasts
  queue: daily_queue
  description: creates a forecast every day at 7am

send_daily_forecast_email:
  cron: 0 12 * * *
  class: DailyForecastEmail
  queue: email_queue
  description: Delivers daily forecast email


# test_daily_forecast:
#   every:
#     - 360s
#     - :first_in: '2s'
#   class: AllForecasts
#   queue: daily_queue
#   description: creates a forecast every day at 7am

# test_daily_forecast_email:
#   every:
#     - 360s
#     - :first_in: '2s'
#   class: DailyForecastEmail
#   queue: email_queue
#   args: 1
#   description: Delivers daily forecast email